### PR TITLE
Ex2: Reformat codes and fix string conversion

### PR DESCRIPTION
**Pull request by quangctkm9207**
- Fix indentation
- Change toString("NO)" -> toString("")

### CODE REVIEW

**Comment by patridge** [comment]
Thank you for your contribution. We'll have to check this out.

Normally, it would be nice to separate any whitespace changes from functional changes in a pull request to make sure the changes warranting discussion are addressed. In this case, the whitespace was mostly uniform with the original Mono Develop defaults, which were relevant when this course was first created. A new course today would probably lean more toward the default Visual Studio 2017 whitespace settings, similar to what you submitted. Either way, there is a functionality change to review.

For that `ToString("N0")` change, I'll need to review the exercise to figure out the intent. Per the [Double.ToString docs](https://msdn.microsoft.com/en-us/library/kfsatb94%28v=vs.110%29.aspx), the original format argument would strip all decimal place values. The default would be `"G"`, which is most of the floating point decimal values. One ("N0") would strip decimal accuracy while the other ("G") would potentially introduce decimal variance from floating point operations.

I'll see if I can get an original author to comment on that particular change.

**Comment by quangctkm9207** [comment]
Thank @patridge for your quick review. 
I just found the string format and whitespace issues while following this course.
It is not a good practice to put indentation and functional changes in a pull request. 
It is nice to hear that the course will get update soon. So, feel free to update by yourself and discard this pull request. 
The final goal is to provide better source codes for later students. Thanks again for maintaining. :D

**Comment by patridge** [comment]
I finally had a chance to rebase and resolve the conflicts in this pull request. Now that I can better tell what changed, I'll start reviewing the proposed changes.

**Comment by patridge** [comment]
The prior logic does seem to be truncating decimal/double values, so I'm going to consider this an improvement. I am going to copy the concepts over to the other Start/Completed exercises and merge.

**Comment by patridge** [comment]
Thanks, again for the help getting this bug fixed, @quangctkm9207.

**Comment by quangctkm9207** [comment]
Thanks @patridge  for merging my PR.

**Pull request merged**
